# This wraps the upstream nginx image so dependabot can watch it for changes.
# If https://github.com/dependabot/dependabot-core/issues/390 is addressed, we
# can just inline this into docker-compose.yml
FROM nginx:stable-alpine@sha256:5b44a5ab8ab467854f2bf7b835a32f850f32eb414b749fbf7ed506b139cd8d6b
