# This wraps the upstream nginx image so dependabot can watch it for changes.
# If https://github.com/dependabot/dependabot-core/issues/390 is addressed, we
# can just inline this into docker-compose.yml
FROM nginx:stable-alpine@sha256:d2c11a1e63f200585d8225996fd666436277a54e8c0ba728fa9afff28f075bd7
